### ISSUE TITLE
[BUG] Re-evaluate where to obtain the Hostname from

### ISSUE THREAD

**Issue by ArjanMyer** [dalgibbard/citrix_xenserver_patcher#28] opened 2014-10-07 14:34 UTC
When the 'name-label' which is displayed in the host-list is for example written in uppercase and the 'hostname' that is derived from /etc/sysconfig/network is written in lower-case then the script is not able to find the UUID. Changing the 'name-label' of the XenServer to lower-case by hand solved the issue. Proposal is to convert the 'name-label' and hostname to lowercase in the script.

**Comment by dalgibbard** [comment] 2015-02-13 09:23
Based on #30 - sounds like we need to reconsider where we get our hostname from again...

**Comment by thctlo** [comment] 2015-03-27 10:53
Hi, im have a look again. 
in commenting on : 
When the 'name-label' which is displayed in the host-list is for example written in uppercase and the 'hostname' that is derived from /etc/sysconfig/network is written in lower-case then the script is not able to find the UUID.

If you change the "name" in XenCenter and not the servers hostname, which i did in my case, than the script wil fail also.
running : xe host-list --minimal is in my opinion sufficient for getting the HOSTUUID.

**Comment by dalgibbard** [comment] 2015-03-27 10:55
I agree with your last point; but not necessarily in cases where the host is part of a pool- pretty sure it returns all pool nodes in that scenario?

**Comment by thctlo** [comment] 2015-03-27 11:06
thats a good one. I dont use pools over here, im running the free xenserver. So i cant test that. 
Im testing now on xen 6.5 
change the code to just : xe host-list params=uuid --minimal 
and ./patcher -l reports nicely all patches back.

**Comment by dalgibbard** [comment] 2015-06-05 15:38
I've merged #36 in now; could someone affected by this confirm if this works as expected now? Any cases where it's still not working as desired? I'm hoping to spend a bit of time on this script the week after next, see if I can get the remaining issues closed off!

**Comment by thctlo** [comment] 2015-06-10 13:08
Ok, i have found the problem in the name detection of patcher i think. 

The problem is, my server has a hostname: TEST-XEN1 
In the XenCenter, i changed that to : TEST-XEN1 192.168.0.1 

This is where the problem is. 
running ./patcher -l 
./patcher.py -l
Getting host list using: /opt/xensource/bin/xe host-list name-label=`grep "^HOSTNAME=" /etc/sysconfig/network | awk -F= '{print$2}'` params=uuid --minimal
Detected HOST UUID: 
Error: Failed to obtain HOSTUUID from XE CLI

running the command : 
xe host-list name-label=`grep "^HOSTNAME=" /etc/sysconfig/network | awk -F= '{print$2}'` params=uuid --minimal
returns nothing. 

xe host-list name-label=TEST-XEN1
same, nothing 

but this one : 
xe host-list name-label='TEST-XEN1 192.168.0.1 ' 
retuns the needed info. 

so if the hostname is different from the name you see in xencenter it fails.
and running : xe host-list name-label='TEST-XEN1 192.168.0.1 '  params=uuid --minimal 
works as it should. 

so if the name-label value in xencenter is different as "hostname" it cant detect the uuid. 
I hope this helps you.

**Comment by carlbb** [comment] 2015-06-11 01:00
Is there a legacy support reason we are using hostname to filter on the name-label to lookup the host UUID ?

The name label seems volatile and descriptive term in xencenter

Can we please use xe host-list hostname switch instead?
xecli host-list name-label=`grep "^HOSTNAME=" /etc/sysconfig/network | awk -F= \'{print$2}\'` params=uuid --minimal')
xecli host-list hostname=`grep "^HOSTNAME=" /etc/sysconfig/network | awk -F= \'{print$2}\'` params=uuid --minimal')

[root@server1~]# xe host-list name-label=server
server1\ Legacy\  Access\ Server 
server2\ Legacy\ Access\ Server 
server3\ Remote\ Access\ Servers 
server4\ Database\ and\ User\ Clients 

[root@server1 ~]# xe host-list hostname=server
server1   server2 server3  server4

**Comment by dalgibbard** [comment] 2015-06-11 07:18
@carlbb - assuming this is supported by XS6.2 onwards; this seems like the best approach, assuming it consistently matches the system/OS hostname?

**Comment by dalgibbard** [comment] 2015-06-16 11:42
I've switched to using ```xe host-list hostname=`` in the code I have here which should be checked in shortly-ish. Seems like the logical approach.

**Comment by dalgibbard** [comment] 2015-06-16 16:54
Change has been committed now; can anyone confirm if this does/doesn't resolve the issue for them?

**Comment by carlbb** [comment] 2015-06-16 23:52
The change has worked on my testing pools
version 6.2 SP1

**Comment by thctlo** [comment] 2015-06-17 06:44
Hai, thanks for the change. ! 
Works great now for me also in a non pool environment. 
Tested on Xen 6.2sp1  and 6.5 and  6.5sp1

**Comment by dalgibbard** [comment] 2015-06-17 06:47
Excellent stuff! I'll close this off for now then; but can reopen if we find it to still be an issue.

**Closed by dalgibbard** 2015-06-17 06:47 UTC
Labels: bug, pending-testing
